# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
# https://docs.flutter.dev/ui/internationalization
arb-dir: lib/l10n
format: true
output-localization-file: app_localizations.dart
template-arb-file: app_en.arb
untranslated-messages-file: lib/l10n/untranslated.txt
