# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#adding-your-own-localized-messages
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart

# runs 'dart format' on generated ".dart_tool/flutter_gen/gen_l10n/app_localizations.dart".
# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#configuring-the-l10n-yaml-file
format: true
