name: flutter_playground
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.10.0
# > The version constraint is optional but recommended. If no version constraint is given, any is assumed.
# https://dart.dev/tools/pub/dependencies#hosted-packages
dependencies:
  async: any # by dart.dev
  collection: any # by dart.dev
  device_info_plus: any # Flutter Favorite
  firebase_analytics: any # by firebase.google.com
  firebase_auth: any # by firebase.google.com and Flutter Favorite
  firebase_core: any # by firebase.google.com and Flutter Favorite
  firebase_crashlytics: any # by firebase.google.com and Flutter Favorite
  firebase_remote_config: any # by firebase.google.com
  firebase_ui_firestore: any # by firebase_ui_firestore and Flutter Favorite
  flutter:
    sdk: flutter
  flutter_launcher_icons: any
  flutter_local_notifications: any # Flutter Favorite
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: any # Flutter Favorite
  flutter_slidable: any # Flutter Favorite
  flutter_svg: any # Flutter Favorite
  freezed_annotation: any
  geolocator: any # Flutter Favorite
  glob: any # by tools.dart.dev
  google_maps_flutter: any # by flutter.dev
  googleapis: any # by google.dev and Flutter Favorite
  http: any # by dart.dev
  image_picker: any # by flutter.dev
  intl: any # by dart.dev and Flutter Favorite
  json_annotation: any # by google.dev
  package_info_plus: any # Flutter Favorite
  path: any # by dart.dev
  path_provider: any # by path_provider and Flutter Favorite
  permission_handler: any
  pub_semver: any # by tools.dart.dev
  rfw: any # by flutter.dev
  riverpod_annotation: any
  shared_preferences: any # by flutter.dev and Flutter Favorite
  stack_trace: any # by tools.dart.dev
  url_launcher: any # by flutter.dev and Fluter Favorite
  video_player: any # by flutter.dev and Flutter Favorite
  webview_flutter: any # flutter.dev
  xml: any
dev_dependencies:
  build_runner: any # by tools.dart.dev
  flutter_lints: any # by flutter.dev
  flutter_test:
    sdk: flutter
  freezed: any # Flutter Favorite
  json_serializable: any # Flutter Favorite
  riverpod_generator: any
  riverpod_lint: any
flutter:
  default-flavor: dev
  generate: true # https://docs.flutter.dev/ui/internationalization#adding-your-own-localized-messages
  uses-material-design: true
  assets:
    - assets/input.rfw
