# Default is false.
# https://developer.android.com/jetpack/androidx
android.builtInKotlin=false
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.enableAppCompileTimeRClass=false
android.newDsl=false
android.r8.optimizedResourceShrinking=false
android.r8.strictFullModeForKeepRules=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.uniquePackageNames=false
android.useAndroidX=true
android.usesSdkInManifest.disallowed=false
# Default is unclear.
# https://kotlinlang.org/docs/code-style-migration-guide.html#in-gradle
kotlin.code.style=official
# The default values of the key "org.gradle.*"
# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx6g
org.gradle.parallel=true
