// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQO5x3I8-kRA0UN3vJhybfShXsyLbho2Y',
    appId: '1:1061012118977:android:229b814e8d6682122b6340',
    messagingSenderId: '1061012118977',
    projectId: 'curious-llc',
    databaseURL: 'https://curious-llc.firebaseio.com',
    storageBucket: 'curious-llc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZZEXivIhKapkCrR5aLdmD8bil8gn7PA',
    appId: '1:1061012118977:ios:b4ed1ce67277dff32b6340',
    messagingSenderId: '1061012118977',
    projectId: 'curious-llc',
    databaseURL: 'https://curious-llc.firebaseio.com',
    storageBucket: 'curious-llc.appspot.com',
    iosBundleId: 'com.example.flutterPlayground1115',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCZZEXivIhKapkCrR5aLdmD8bil8gn7PA',
    appId: '1:1061012118977:ios:2eef612451f98aa32b6340',
    messagingSenderId: '1061012118977',
    projectId: 'curious-llc',
    databaseURL: 'https://curious-llc.firebaseio.com',
    storageBucket: 'curious-llc.appspot.com',
    iosBundleId: 'com.example.flutterPlayground.RunnerTests',
  );
}
