on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart format -o none --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test
